# Generated by Django 4.2.11 on 2024-06-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookmark", old_name="created_at", new_name="date",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="cloud",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="isscrape",
            field=models.BooleanField(default=False),
        ),
    ]
