# Generated by Django 4.2.11 on 2024-06-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_scrape"),
    ]

    operations = [
        migrations.DeleteModel(name="Scrape",),
    ]
