# Generated by Django 4.2.11 on 2024-06-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_alter_article_date_alter_article_title"),
    ]

    operations = [
        migrations.DeleteModel(name="Article",),
    ]
